name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: ssh -p 22 root@206.191.151.187 "cd /var/www/html/my-stuff; git pull; exit"

        
